openapi: '3.0.2'
info:
  title: SkillsBuildSearch
  description: An AI IBM SkillsBuild search tool
  version: '1.0.0'
servers:
  - url: https://squareearth.net
paths:
  /api/v1/search:
    get:
      parameters:
        - name: text
          in: query
          required: true
          description: Plaintext HE course description search query
          schema:
            type: string
            minLength: 12
        - name: offset
          in: query
          required: true
          description: Course offsets
          schema:
            type: integer
            minimum: 0
      summary: Returns courses[offset:offset + default_offset_length] for a given HE course description
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    Title:
                      type: string
                    Description_short:
                      type: string
                    Link:
                      type: string
                    Topic:
                      type: string
        "400":
          description: Returns an error description and code, code 1 is for a critical error and code 2 is for a warning
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  code:
                    type: integer
                    enum: [1, 2]
  /api/v1/categories:
    get:
      summary: Returns a list of all course categories
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /api/v1/stt:
    post:
      summary: Returns a transcript of an audio file of speech
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: string
        "400":
          description: Returns an error description and code, code 1 is for a critical error and code 2 is for a warning
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  code:
                    type: integer
                    enum: [1, 2]